# Generated by Django 5.2.15 on 2026-07-21 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descripcion', models.TextField()),
                ('peso', models.FloatField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('OFICINA', 'En oficina'), ('TRANSPORTE', 'En transporte'), ('ENTREGADO', 'Entregado')], default='OFICINA', max_length=20)),
                ('transporte', models.CharField(choices=[('BUS', 'Bus'), ('CAMIONETA', 'Camioneta'), ('MOTO', 'Moto')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Envio.cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Envio.destino')),
            ],
        ),
    ]
