# Generated by Django 5.2.15 on 2026-07-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='codigo_postal',
            field=models.CharField(default=550555, max_length=6),
            preserve_default=False,
        ),
    ]
