# Generated by Django 6.0.6 on 2026-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envio', '0002_destino_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='cedula_destinatario',
            field=models.CharField(default=1232123212, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='email_destinatario',
            field=models.EmailField(default='jh@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='nombre_destinatario',
            field=models.CharField(default='Julian', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='telefono_destinatario',
            field=models.CharField(default='0909898789', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
