# Generated by Django 5.0.6 on 2026-07-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Envio', '0004_destino_cedula_destinatario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomienda',
            name='cedula_destinatario',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='email_destinatario',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='nombre_destinatario',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='telefono_destinatario',
        ),
    ]
