# Generated by Django 6.0.6 on 2026-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envio', '0006_alter_cliente_id_alter_destino_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='cedula_destinatario',
            field=models.CharField(default=1231231232, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='email_destinatario',
            field=models.EmailField(default='j@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='nombre_destinatario',
            field=models.CharField(default='juliana', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='telefono_destinatario',
            field=models.CharField(default=1231231232, max_length=15),
            preserve_default=False,
        ),
    ]
